### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by andersoonluan** [nztim/simplehttp#1]
This package is not found using the follow command below

`composer require nztim/simplehttp`

Error:
The requested package nztim/simplehttp could not be found in any version, there may be a typo in the package name

**Comment by nztim** [comment]
It's not available via Packagist because while you're welcome to use it, it's primarily for my own projects and I'm not promoting it. 

It's based on https://github.com/kitetail/zttp which you can get the normal way. If you want to use this then you have to add the repository to your `composer.json`:

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nztim/simplehttp"
        }
],
```
I will update the readme accordingly.
